---
- name: Setup necessary packages
  hosts: "{{ hosts }}"
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install OS essentials
      apt:
        name: "{{ item }}"
        update_cache: yes
      ignore_errors: true
      with_items:
        - git
        - python3.11
        - nginx
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: true
    - name: Setup ssh private key
      copy:
        src: "{{ ssh_private_file }}"
        dest: /home/azureuser/.ssh/id_ed25519
      tags: [ssh]
    - name: Setup ssh public
      copy:
        src: "{{ ssh_pub_file }}"
        dest: /home/azureuser/.ssh/id_ed25519.pub
      tags: [ssh]
    - name: Add github to known hosts
      shell: "ssh-keyscan github.com >> ~/.ssh/known_hosts"
      tags: [ssh]
